### ISSUE TITLE
Add links to readme

### ISSUE THREAD

**Issue by melMass** [thomas694/iPhoneMediaTransfer#1]
Thanks I would just add links to the old installer: https://support.apple.com/kb/DL2065

And also is this the right dll? 
![image](https://github.com/thomas694/iPhoneMediaTransfer/assets/7041726/9300cfcf-9bf3-4610-a181-332f799680ca)

Thanks

**Comment by melMass** [comment]
Ah seems like this is a much more recent version, I did not see the 1 vs 10 diff!

I got 12.1.1 from 
https://ipsw.me/iTunes

And the dll is here:
![image](https://github.com/thomas694/iPhoneMediaTransfer/assets/7041726/e04299fb-5e8c-42dc-9f13-da36ce2b67de)

**Comment by thomas694** [comment]
The last time I searched there was no longer an official download for these packages, therefore I hadn't given any specific download links, but described what's required in which version. So everyone could download from his preferred source of archived apps.

But a new search just gave me a site with the direct links:
[The iPhone Wiki](https://www.theiphonewiki.com/wiki/ITunes)
I linked that one.

**Comment by melMass** [comment]
Great thank you!!
