### ISSUE TITLE
Trash photos import

### ISSUE THREAD

**Issue by axel9546** [thomas694/iPhoneMediaTransfer#2]
Hi, is there a way to use the script to import also "deleted images", so the "trash" iphone local or cloud folder?

**Comment by thomas694** [comment]
Hello, the tool is not connecting to the cloud, only locally to the device. Media inside the trash bin is copied to the folder "DCIM_deleted" on disk.

**Comment by axel9546** [comment]
> Hello, the tool is not connecting to the cloud, only locally to the device. Media inside the trash bin is copied to the folder "DCIM_deleted" on disk.

 
In the case i'd like to exclude a folder, for example "DCIM_deleted", how would I use the command? iPhoneMediaTransfer [options] <folder>
Is there an options only to copy a specific "sourcefolder"?

**Comment by thomas694** [comment]
It always replicates the whole structure by transferring missing items. There's no option to exclude specific folders.
