### ISSUE TITLE
.exe

### ISSUE THREAD

**Issue by tom-vb** [thomas694/iPhoneMediaTransfer#3]
Would it be possible for the author to post an executable? This software is what I was looking for, but I do not have the knowledge or tools to compile and use it.

**Comment by thomas694** [comment]
I can provide [this](https://github.com/thomas694/iPhoneMediaTransfer/releases) if it helps you.
You still need to copy the iTunesMobileDevice.dll to the exe folder and install the two packages as described.

**Comment by tom-vb** [comment]
Many thanks Thomas, I will try!
