### ISSUE TITLE
iOS Device Disconnected.

### ISSUE THREAD

**Issue by phi0x** [thomas694/iPhoneMediaTransfer#5]
i'm trying to connect to a iphone 6s which has a broken screen so I can try and recover the photos.

when running with -media flag it just says:
iOS Device Disconnected.

I've tried various usb 2.0 and 3.1 ports but same issue. I can see the 'apple iphone' in windows explorer and the drive showing there's 3gb free out of 29gb but no photos show in the explorer. Not sure if I need to be able to do the 'trust this device' prompt that would be on the iphone when connecting to a pc in order to get the photos?

**Comment by thomas694** [comment]
I'm not sure if 6s is supported.

If the "device disconnected" message appears, simply unplug the cable and plug it back in (repeat twice if necessary). In other cases, the tool must be restarted first.
Downloading with Explorer can be a bit cumbersome. Connect the phone, confirm the 'trust this device' prompt and check that the phone icon is displayed (or open it and wait in the empty folder). Then wait several(!) minutes and suddenly there are entries in the folder.
In order for a PC to connect, you must confirm "trust this device" when prompted.

**Comment by phi0x** [comment]
Thanks, yes it seems I need to replace the screen so I can access the "Trust your device" button, then it should work.
